#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import sqlite3
from dataclasses import dataclass
from pathlib import Path


SCRIPT_PATH = Path(__file__).resolve()
REPO_ROOT = SCRIPT_PATH.parents[1]
MANIFEST_PATH = REPO_ROOT / "agents" / "manifest.json"
DEFAULT_DB_PATH = Path(os.path.expanduser("~/.den-mcp/den.db"))


@dataclass(frozen=True)
class Manifest:
    output_file: str
    local_fragment_file: str
    shared_fragments: list[str]


@dataclass(frozen=True)
class ProjectTarget:
    project_id: str
    root_path: Path


def load_manifest() -> Manifest:
    data = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    return Manifest(
        output_file=data["output_file"],
        local_fragment_file=data["local_fragment_file"],
        shared_fragments=list(data["shared_fragments"]),
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate AGENTS.md from shared den-mcp fragments and a project-local agents-project.md fragment."
    )
    parser.add_argument("--project-id", help="Generate AGENTS.md for one Den-registered project id.")
    parser.add_argument("--root", help="Generate AGENTS.md for one explicit project root.")
    parser.add_argument("--all", action="store_true", help="Generate AGENTS.md for every opted-in Den-registered project.")
    parser.add_argument("--db-path", default=str(DEFAULT_DB_PATH),
                        help="Path to the Den SQLite database used for project-id and --all resolution.")
    parser.add_argument("--check", action="store_true",
                        help="Check whether output is up to date instead of writing files.")
    return parser.parse_args()


def validate_args(args: argparse.Namespace) -> None:
    selected = sum(bool(value) for value in (args.project_id, args.root, args.all))
    if selected > 1:
        raise SystemExit("Choose only one of --project-id, --root, or --all.")


def load_project_by_id(db_path: Path, project_id: str) -> ProjectTarget:
    connection = open_den_db(db_path)
    try:
        try:
            row = connection.execute(
                "SELECT id, root_path FROM projects WHERE id = ? AND root_path IS NOT NULL",
                (project_id,),
            ).fetchone()
        except sqlite3.Error as ex:
            raise SystemExit(f"Failed to query Den projects from {db_path}: {ex}") from ex
    finally:
        connection.close()

    if row is None:
        raise SystemExit(f"Project '{project_id}' was not found in {db_path} with a non-null root_path.")

    return ProjectTarget(project_id=row[0], root_path=Path(row[1]).expanduser().resolve())


def load_all_projects(db_path: Path) -> list[ProjectTarget]:
    connection = open_den_db(db_path)
    try:
        try:
            rows = connection.execute(
                """
                SELECT id, root_path
                FROM projects
                WHERE id != '_global' AND root_path IS NOT NULL
                ORDER BY id ASC
                """
            ).fetchall()
        except sqlite3.Error as ex:
            raise SystemExit(f"Failed to query Den projects from {db_path}: {ex}") from ex
    finally:
        connection.close()

    return [ProjectTarget(project_id=row[0], root_path=Path(row[1]).expanduser().resolve()) for row in rows]


def read_fragment(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip()


def build_output(manifest: Manifest, project_root: Path) -> str:
    local_fragment_path = project_root / manifest.local_fragment_file
    if not local_fragment_path.exists():
        raise FileNotFoundError(f"Missing local fragment: {local_fragment_path}")

    shared_fragment_paths = [REPO_ROOT / relative for relative in manifest.shared_fragments]
    missing_shared = [path for path in shared_fragment_paths if not path.exists()]
    if missing_shared:
        joined = ", ".join(str(path) for path in missing_shared)
        raise FileNotFoundError(f"Missing shared fragment(s): {joined}")

    fragments: list[str] = [read_fragment(local_fragment_path)]
    fragments.extend(read_fragment(path) for path in shared_fragment_paths)

    header_lines = [
        "# AGENTS.md (Autogenerated)",
        "",
        "> WARNING: This file is autogenerated by `scripts/generate_agents.py`. Do not edit it directly.",
        f"> Edit the project-local fragment `{manifest.local_fragment_file}` and the shared fragments under `den-mcp/agents/shared/`, then regenerate.",
        ">",
        "> Generation sources:",
    ]
    for relative in manifest.shared_fragments:
        header_lines.append(f"> - shared: `{relative}`")
    header_lines.append(f"> - local: `{manifest.local_fragment_file}`")
    header_lines.append("")

    parts = ["\n".join(header_lines)]
    parts.extend(fragments)
    return "\n\n".join(part.rstrip() for part in parts).rstrip() + "\n"


def write_or_check(project: ProjectTarget, manifest: Manifest, check: bool) -> tuple[str, bool]:
    output_path = project.root_path / manifest.output_file
    expected = build_output(manifest, project.root_path)
    current = output_path.read_text(encoding="utf-8") if output_path.exists() else None
    changed = current != expected

    if check:
        status = "OUTDATED" if changed else "OK"
    else:
        output_path.write_text(expected, encoding="utf-8")
        status = "UPDATED" if changed else "UNCHANGED"

    return status, changed


def main() -> int:
    args = parse_args()
    validate_args(args)
    manifest = load_manifest()
    db_path = Path(args.db_path).expanduser().resolve()

    if args.all:
        projects = load_all_projects(db_path)
    elif args.project_id:
        projects = [load_project_by_id(db_path, args.project_id)]
    elif args.root:
        root_path = Path(args.root).expanduser().resolve()
        projects = [ProjectTarget(project_id=root_path.name, root_path=root_path)]
    else:
        projects = [ProjectTarget(project_id="den-mcp", root_path=REPO_ROOT)]

    had_outdated = False
    processed = 0
    skipped = 0

    for project in projects:
        local_fragment_path = project.root_path / manifest.local_fragment_file
        if not local_fragment_path.exists():
            if args.all:
                print(f"SKIP {project.project_id}: missing {manifest.local_fragment_file}")
                skipped += 1
                continue
            raise SystemExit(f"Missing local fragment: {local_fragment_path}")

        status, changed = write_or_check(project, manifest, check=args.check)
        print(f"{status} {project.project_id}: {project.root_path / manifest.output_file}")
        processed += 1
        had_outdated = had_outdated or changed

    if args.check and had_outdated:
        return 1

    if args.all:
        print(f"Processed {processed} project(s); skipped {skipped} without {manifest.local_fragment_file}.")

    return 0


def open_den_db(db_path: Path) -> sqlite3.Connection:
    if not db_path.exists():
        raise SystemExit(f"Den database not found: {db_path}")

    try:
        return sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    except sqlite3.Error as ex:
        raise SystemExit(f"Failed to open Den database {db_path}: {ex}") from ex


if __name__ == "__main__":
    raise SystemExit(main())
