from __future__ import annotations

import pathlib
import sqlite3
import subprocess
import tempfile
import unittest


REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
SCRIPT_PATH = REPO_ROOT / "scripts" / "generate_agents.py"


class GenerateAgentsTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temp_dir = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp_dir.cleanup)
        self.root = pathlib.Path(self.temp_dir.name)
        self.db_path = self.root / "den.db"

        connection = sqlite3.connect(self.db_path)
        try:
            connection.execute(
                """
                CREATE TABLE projects (
                    id TEXT PRIMARY KEY,
                    root_path TEXT
                )
                """
            )
        finally:
            connection.close()

    def make_project(self, project_id: str, include_local_fragment: bool = True) -> pathlib.Path:
        root = self.root / project_id
        root.mkdir(parents=True)
        if include_local_fragment:
            (root / "agents-project.md").write_text(
                f"## Project Context\n\nThis is {project_id}.\n",
                encoding="utf-8",
            )

        connection = sqlite3.connect(self.db_path)
        try:
            connection.execute(
                "INSERT INTO projects (id, root_path) VALUES (?, ?)",
                (project_id, str(root)),
            )
            connection.commit()
        finally:
            connection.close()

        return root

    def run_script(self, *args: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            ["python3", str(SCRIPT_PATH), *args],
            cwd=REPO_ROOT,
            text=True,
            capture_output=True,
            check=False,
        )

    def test_root_generation_writes_den_bootstrap_and_local_fragment(self) -> None:
        project_root = self.make_project("sample-project")

        result = self.run_script("--root", str(project_root))
        self.assertEqual(result.returncode, 0, result.stderr)

        generated = (project_root / "AGENTS.md").read_text(encoding="utf-8")
        self.assertIn("# AGENTS.md (Autogenerated)", generated)
        self.assertIn("Do not edit it directly", generated)
        self.assertIn("get_agent_guidance(project_id=\"sample-project\")", generated)
        self.assertIn("## Den Guidance Bootstrap", generated)
        self.assertIn("Project ID: `sample-project`", generated)
        self.assertIn("If Den is unreachable, stop and tell the user", generated)
        self.assertIn("## Project Context", generated)
        self.assertNotIn("## Task Management", generated)
        self.assertNotIn("## Review Loop", generated)
        self.assertTrue(generated.endswith("\n"))

    def test_project_id_generation_uses_den_db_lookup(self) -> None:
        project_root = self.make_project("lookup-project")

        result = self.run_script("--project-id", "lookup-project", "--db-path", str(self.db_path))
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertTrue((project_root / "AGENTS.md").exists())

    def test_all_generation_skips_projects_without_local_fragment(self) -> None:
        opted_in_root = self.make_project("opted-in")
        skipped_root = self.make_project("skipped-project", include_local_fragment=False)

        result = self.run_script("--all", "--db-path", str(self.db_path))
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("SKIP skipped-project", result.stdout)
        self.assertIn("Processed 1 project(s); skipped 1", result.stdout)
        self.assertTrue((opted_in_root / "AGENTS.md").exists())
        self.assertFalse((skipped_root / "AGENTS.md").exists())

    def test_check_mode_fails_when_output_is_outdated(self) -> None:
        project_root = self.make_project("check-project")
        (project_root / "AGENTS.md").write_text("stale\n", encoding="utf-8")

        result = self.run_script("--root", str(project_root), "--check")
        self.assertEqual(result.returncode, 1)
        self.assertIn("OUTDATED check-project", result.stdout)

    def test_project_id_generation_fails_cleanly_when_db_is_missing(self) -> None:
        missing_db = self.root / "missing.db"

        result = self.run_script("--project-id", "lookup-project", "--db-path", str(missing_db))
        self.assertEqual(result.returncode, 1)
        self.assertIn("Den database not found", result.stderr)


if __name__ == "__main__":
    unittest.main()
